services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql
    environment:
      # Root variables are required
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - ./initdb-mysql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    ports:
      - "15432:5432"
    volumes:
      - ./initdb-postgres:/docker-entrypoint-initdb.d
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
volumes:
  mysql_data:
  postgres_data:
